FROM openjdk:11-jre-slim

RUN mkdir -p /app

WORKDIR /app

COPY ./target/yasn-backend-1.0.0-SNAPSHOT.jar /app/

EXPOSE 8000

ENTRYPOINT ["java", "-jar", "-Dspring.profiles.active=prod", "yasn-backend-1.0.0-SNAPSHOT.jar"]