# Build stage
FROM node:lts-alpine AS build

WORKDIR /app

COPY package*.json ./
COPY yarn.lock ./

RUN yarn install

COPY ./ ./

RUN yarn build

# Production stage
FROM nginx:alpine

COPY --from=build /app/dist/yasn-frontend /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
