export const EndpointUrls = {
  websocketTopicCreatedNewPost: "/new-post-created",
  websocketNotificationFriendRequest: "/new-friend-request",
  websocketStompFactory: "wss://localhost:8000/ws",
  websocketSockJSFactory: "http://localhost:8000/stomp",
  loginUser: "/api/user/login",
  registerUser: "/api/user/register",
  postToPublicWall: "/api/home/news-feed/post",
  pullAllNews: "/api/home/all-news/",
  notifications: "/api/notification",
  postComment: "/api/home/news-feed/post/comment",
  likeAPost: "/api/actions/likes/likeAPost",
  unLikeAPost: "/api/actions/likes/unLikeAPost",
  userProfileTimeline: "/api/user-profile/timeline/",
  userProfileGuest: "/api/user-profile/guest/",
  selectUserProfile: "/api/user-profile/",
  sendFriendRequest: "/api/notification/send-friend-request",
  acceptFriendRequest: "/api/notification/accept-friend/",
  addFriend: "/api/actions/add-friend",
  unfriendRequest: "/api/notification/unfriend/",
}
